env:
  browser: true
  es2021: true
  node: true

extends:
  - eslint:recommended

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  # Possible problems
  no-unused-vars: error
  no-undef: error

  # Suggestions
  prefer-const: error
  no-var: error

  # Layout & Formatting
  indent:
    - error
    - 2
  quotes:
    - error
    - single
  semi:
    - error
    - never
